/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Maps;

import MapsLogic.*;

public class App extends Engine {

    public App() {
        super();
    }

    public App(int noOfCities) throws Exception {
        super(noOfCities);
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App obj = new App();
        System.out.println(obj.rawMap());
        System.out.println(obj.getGreeting());

    }
}
